---
nginx_remove_default_vhost: true
nginx_vhosts:
  - filename: "skeleton.conf"
    server_name: "skeleton skeleton.local"
    root: "/var/www/skeleton/public"
    access_log: "/var/log/nginx/skeleton.access.log"
    error_log: "/var/log/nginx/skeleton.error.log"
    extra_parameters: |
      location / {
          try_files $uri /index.php$is_args$args;
      }

      location ~ ^/index\.php(/|$) {
          fastcgi_pass unix:/run/php/php-fpm.sock;
          fastcgi_split_path_info ^(.+\.php)(/.*)$;
          include fastcgi_params;

          fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
          fastcgi_param DOCUMENT_ROOT $realpath_root;

          # Prevents URIs that include the front controller. This will 404:
          # http://domain.tld/index.php/some-path
          # Remove the internal directive to allow URIs like this
          internal;
      }

      location ~ \.php$ {
          return 404;
      }

nginx_multi_accept: "on"
nginx_keepalive_timeout: "15"
nginx_server_tokens: "off"