core:
  validator:
    schema:
      declare:
        - path: '@CoreBundle/Resources/schema/'
          prefix: 'https://skeleton.com/Core/'
#      format:
#        - Core\Infrastructure\FormatValidator\ValueObject\XXX