doctrine:
    dbal:
#        url: '%env(resolve:DATABASE_URL)%'
        dbname: '%env(resolve:DATABASE_BD)%'
        host: '%env(resolve:DATABASE_HOST)%'
        port: '%env(resolve:DATABASE_PORT)%'
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'
        driver: '%env(resolve:DATABASE_DRIVER)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true

        dql:
            string_functions:
                JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract
                JSON_SEARCH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonSearch
                JSON_CONTAINS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains

        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/App/src/Entity'
                prefix: 'App\Entity'
                alias: App
            CoreBundle:
                is_bundle: true
                type: yml
                dir: 'Resources/config/doctrine'
                prefix: 'Core\Domain\Entity'
            AuthBundle:
                is_bundle: true
                type: yml
                dir: 'Resources/config/doctrine'
                prefix: 'Auth\Domain\Entity'
