---
# fzf
zsh_fzf_height: "40%"
zsh_fzf_reverse: yes
zsh_fzf_border: yes
zsh_fzf_ctrl_r_opts: '--exact'

zsh_user_group: "{% if ansible_os_family == 'Darwin' %}staff{% else %}{{ zsh_user }}{% endif %}"
zsh_antigen_path: "{% if zsh_shared %}/usr/share/zsh-config{% else %}~{{ zsh_user }}/.antigen{% endif %}"
zsh_config: "{% if zsh_shared %}/usr/share/zsh-config/.zshrc{% else %}~{{ zsh_user }}/.zshrc{% endif %}"
zsh_config_folder: "{% if zsh_shared %}/usr/share/zsh-config/{% else %}~{{ zsh_user }}/{% endif %}"
zsh_antigen_path_compat: "{{ zsh_antigen_path | replace('~' + zsh_user, '$HOME') }}"

zsh_fzf_os: linux
zsh_fzf_arch: "{% if '64' in ansible_architecture %}amd64{% else %}386{% endif %}"
zsh_fzf_url: "https://github.com/junegunn/fzf-bin/releases/download/{{ zsh_fzf_version }}/fzf-{{ zsh_fzf_version }}-{{ zsh_fzf_os }}_{{ zsh_fzf_arch }}.tgz"
zsh_antigen_fzf_path: "{{ zsh_antigen_path }}/repos/https-COLON--SLASH--SLASH-github.com-SLASH-junegunn-SLASH-fzf.git"
zsh_fzf_default_opts: "--height {{ zsh_fzf_height }}{% if zsh_fzf_reverse %} --reverse{% endif %}{% if zsh_fzf_border %} --border{% endif %}"

zsh_powerlevel9k_prompt_on_newline_bool: "{% if zsh_powerlevel9k_prompt_on_newline %}true{% else %}false{% endif %}"
zsh_powerlevel9k_always_show_context_bool: "{% if zsh_powerlevel9k_always_show_context %}true{% else %}false{% endif %}"
zsh_powerlevel9k_always_show_user_bool: "{% if zsh_powerlevel9k_always_show_user %}true{% else %}false{% endif %}"

zsh_antigen_bundles_extras:
  - git
  - heroku
#  - pip
  - lein
#  - command-not-found
  - common-aliases
#  - fancy-ctrl-z
  - encode64
#  - git-extras
  - gitfast
  - git-flow
#  - gnu-utils
#  - systemd
  - systemadmin
#  - zsh_reload
  - fzf
  - zsh-interactive-cd
  - colored-man-pages
  - composer
#  - kubectl
  - sublime
#  - vagrant
#  - zsh-users/zsh-autosuggestions
  - popstas/zsh-command-time
  - zsh-users/zsh-syntax-highlighting

zsh_antigen_theme: "romkatv/powerlevel10k"
