---
# tasks file for adriagalin.timezone
- name: timezone | set /etc/timezone
  template:
    src: etc/timezone.j2
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
  notify: timezone | update tzdata
  tags: [ common, timezone ]
