---
workspace: /root

php_xdebug_version: 3.0.4

php_xdebug_coverage_enable: 1
php_xdebug_default_enable: 1

php_xdebug_remote_enable: "true"
php_xdebug_remote_connect_back: "true"
php_xdebug_remote_host: nemuru.local
php_xdebug_remote_port: "9000"
#php_xdebug_remote_log: /tmp/xdebug.log
php_xdebug_remote_autostart: "on"
php_xdebug_remote_timeout: 3600

php_xdebug_idekey: PHPSTORM

php_xdebug_max_nesting_level: 256

# Only used on Debian/Ubuntu.
php_xdebug_cli_disable: false
