controllers:
    resource: ../src/App/src/Controller/
    type: annotation

kernel:
    resource: ../src/App/src/Kernel.php
    type: annotation

app_health_check:
    resource: App\Controller\HealthCheckController
    prefix: /app/health-check/
