controllers:
    resource: ../src/App/src/Controller/
    type: annotation

kernel:
    resource: ../src/App/src/Kernel.php
    type: annotation

app_health_check:
    resource: App\Controller\HealthCheckController
    prefix: /api/app/health-check/

core-api:
    resource: '@CoreBundle/Resources/config/routes-api.yaml'
    prefix: /api/core/

core-web:
    resource: '@CoreBundle/Resources/config/routes-web.yaml'
    prefix: /web/core/

auth:
    resource: '@AuthBundle/Resources/config/routes.yaml'
    prefix: /api/auth/