controllers:
    resource: ../src/App/src/Controller/
    type: annotation

kernel:
    resource: ../src/App/src/Kernel.php
    type: annotation

app_health_check:
    resource: App\Controller\HealthCheckController
    prefix: /api/app/health-check/

core:
    resource: '@CoreBundle/Resources/config/routes.yaml'
    prefix: /api/core/

auth:
    resource: '@AuthBundle/Resources/config/routes.yaml'
    prefix: /api/auth/