Auth\Domain\Entity\User:
    type: entity
    table: user
    repositoryClass: Auth\Infrastructure\Repository\Doctrine\DoctrineUserRepository

    id:
        id:
            type: Uuid

    fields:
        email:
            type: string
            length: 128
            unique: true
        roles:
            type: json
        password:
            type: string
        isVerified:
            type: boolean

        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
            hard_delete: true
