admin_health_check:
  resource: Admin\Interfaces\Controller\HealthCheckController
  prefix: /health-check/

auth:
  resource: Admin\Interfaces\Controller\AuthController
  prefix: /auth/

admin:
  resource: Admin\Interfaces\Controller\AdminController
  prefix: /

page_sample:
  resource: Admin\Interfaces\Controller\AdminPageSampleController
  prefix: /page/sample/